version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  fastapi:
    build: .
    container_name: fastapi-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    restart: always
    networks:
      - backend_network

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6380:6379"
    restart: always
    networks:
      - backend_network

networks:
  backend_network:
     external: true

volumes:
  postgres_data:
