version: '3.8'

services:
  bot:
    build: .
    container_name: aiogram_bot
    restart: always
    env_file:
      - .env
    networks:
      - backend_network

networks:
  backend_network:
    external: true
